/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Imperator
 */
public class FrAdminAddBook extends javax.swing.JFrame {

    /**
     * Creates new form FrRegistration
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    public FrAdminAddBook() {
        labelBackground();
        initComponents();
        tfldID.setText(String.valueOf(incrementID()));
    }
    
    public void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/las/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(255, 223, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void connectDatabase(){
        try{
            String strURL = "jdbc:mysql://localhost:3306/ls?useLegacyDatetimeCode=false&serverTimezone=UTC";
            String strDatabaseUsername = "root";
            String strDatabasePassword = "";
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
            System.out.println(error);
        }
    }
    
    public int incrementID(){
        String strID;
        int intID = 0;
        connectDatabase();
        String strquery = "SELECT book_ID FROM BookList ORDER BY book_ID";
        try{
            pstmtMain = conMain.prepareStatement(strquery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                strID = rsMain.getString("book_ID");
                intID = Integer.parseInt(strID)+1;
            }
        }
        catch(SQLException error){
            System.out.println(error);
        }
        if(intID == 0){
            return 190000;
        }
        else{
            return intID;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfldID = new javax.swing.JTextField();
        tfldName = new javax.swing.JTextField();
        tfldAuthor = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tfldID.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldID.setEnabled(false);

        tfldName.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldName.setText("Input Book Name");
        tfldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldNameFocusLost(evt);
            }
        });

        tfldAuthor.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldAuthor.setText("Input Author Name");
        tfldAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldAuthorFocusLost(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(241, 209, 165));
        btnAdd.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(241, 209, 165));
        btnCancel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfldAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(tfldName)
                    .addComponent(tfldID))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldNameFocusLost
        if(tfldName.getText().equals("")){
            tfldName.setText("Input Book Name");
        }
    }//GEN-LAST:event_tfldNameFocusLost

    private void tfldAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldAuthorFocusLost
        if(tfldAuthor.getText().equals("")){
            tfldAuthor.setText("Input Author Name");
        }
    }//GEN-LAST:event_tfldAuthorFocusLost

    private void tfldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldNameFocusGained
        if(tfldName.getText().equals("Input Book Name")){
            tfldName.setText("");
        }
    }//GEN-LAST:event_tfldNameFocusGained

    private void tfldAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldAuthorFocusGained
        if(tfldAuthor.getText().equals("Input Author Name")){
            tfldAuthor.setText("");
        }
    }//GEN-LAST:event_tfldAuthorFocusGained

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        connectDatabase();
        String strID = tfldID.getText();
        String strName = tfldName.getText();
        String strAuthor = tfldAuthor.getText();
        String strQuery = "INSERT INTO"
                + " BookList (book_ID, book_Name, book_Author)"
                + " values("+strID+", '"+strName+"', '"+strAuthor+"')";
        if(strName.equals("")||strAuthor.equals("")){
            JOptionPane.showMessageDialog(null, "Fields must not be Blank.");
        }
        else{
            try{
                pstmtMain = conMain.prepareStatement(strQuery);
                pstmtMain.execute();
                new FrAdminHomePage().setVisible(true);
                this.dispose();
            }
            catch(SQLException error){
                System.out.println(error);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new FrAdminHomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrAdminAddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField tfldAuthor;
    private javax.swing.JTextField tfldID;
    private javax.swing.JTextField tfldName;
    // End of variables declaration//GEN-END:variables
}
