/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Imperator
 */
public class FrLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    public FrLogin() {
        labelBackground();
        initComponents();
        connectDatabase();
    }
    
    public void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/las/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(404, 296, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void createDatabase(){
        String strURL = "jdbc:mysql://localhost:3306/ls?useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true";
        String strQueryBookList = "CREATE TABLE `BookList`("
                + "`book_ID` INT(255) NOT NULL PRIMARY KEY,"
                + "`book_Name` VARCHAR(255),"
                + "`book_Author` VARCHAR(255)"
                + ")";
        String strQueryStudentList = "CREATE TABLE `StudentList`("
                + "`student_ID` INT(255) NOT NULL PRIMARY KEY,"
                + "`student_LName` VARCHAR(255),"
                + "`student_FName` VARCHAR(255),"
                + "`student_Username` VARCHAR(255),"
                + "`student_Password` VARCHAR(255)"
                + ")";
        String strDatabaseUsername = "root";
        String strDatabasePassword = "";
        try{
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
            pstmtMain = conMain.prepareStatement(strQueryBookList);
            pstmtMain.execute();
            pstmtMain = conMain.prepareStatement(strQueryStudentList);
            pstmtMain.execute();
            connectDatabase();
        }
        catch(SQLException error){
            System.out.println(error);
        }
    }
    
    public void connectDatabase(){
        String strURL = "jdbc:mysql://localhost:3306/ls?useLegacyDatetimeCode=false&serverTimezone=UTC";
        String strDatabaseUsername = "root";
        String strDatabasePassword = "";
        try{
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
            createDatabase();
            System.out.println(error);
        }
    }
    
    public int getID(String strUsername, String strPassword){
        connectDatabase();
        String strQuery = "SELECT student_ID, student_Username, student_Password FROM studentlist ORDER BY student_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                if(rsMain.getString("student_Username").equals(strUsername) && rsMain.getString("student_Password").equals(strPassword)){
                    return Integer.parseInt(rsMain.getString("student_ID"));
                }
            }
            if(tfldUsername.getText().equals("ADMIN")&&pfldPassword.getText().equals("ADMIN")){
                return 1;
            }
        }
        catch(SQLException error){
            createDatabase();
            System.out.println(error);
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfldUsername = new javax.swing.JTextField();
        pfldPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tfldUsername.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        tfldUsername.setText("Input Username");
        tfldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldUsernameFocusLost(evt);
            }
        });
        tfldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfldUsernameActionPerformed(evt);
            }
        });

        pfldPassword.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        pfldPassword.setText("()()()");
        pfldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfldPasswordFocusLost(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(241, 209, 165));
        btnLogin.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/las/images/library64.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(241, 209, 165));
        btnRegister.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/las/images/student.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(241, 209, 165));
        btnExit.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister))
                    .addComponent(pfldPassword)
                    .addComponent(tfldUsername))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tfldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister))
                .addGap(4, 4, 4)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        new FrStudentRegistration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tfldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldUsernameFocusGained
        if(tfldUsername.getText().equals("Input Username")){
            tfldUsername.setText("");
        }
    }//GEN-LAST:event_tfldUsernameFocusGained

    private void tfldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldUsernameFocusLost
        if(tfldUsername.getText().equals("")){
            tfldUsername.setText("Input Username");
        }
    }//GEN-LAST:event_tfldUsernameFocusLost

    private void pfldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfldPasswordFocusGained
        if(pfldPassword.getText().equals("()()()")){
            pfldPassword.setText("");
        }
    }//GEN-LAST:event_pfldPasswordFocusGained

    private void pfldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfldPasswordFocusLost
        if(pfldPassword.getText().equals("")){
            pfldPassword.setText("()()()");
        }
    }//GEN-LAST:event_pfldPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String strUsername = tfldUsername.getText();
        String strPassword = pfldPassword.getText();
        int intID = getID(strUsername, strPassword);
        if(intID != 0 && intID != 1){
            new FrStudentHomePage(intID).setVisible(true);
            this.dispose();
        }
        else if(intID == 1){
            new FrAdminHomePage().setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Incorrect Credentials.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField pfldPassword;
    private javax.swing.JTextField tfldUsername;
    // End of variables declaration//GEN-END:variables
}
