/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Imperator
 */
public class FrStudentRegistration extends javax.swing.JFrame {

    /**
     * Creates new form FrRegistration
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    public FrStudentRegistration() {
        labelBackground();
        initComponents();
        tfldID.setText(String.valueOf(incrementID()));
    }
    
    public void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/las/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(202, 304, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void connectDatabase(){
        try{
            String strURL = "jdbc:mysql://localhost:3306/ls?useLegacyDatetimeCode=false&serverTimezone=UTC";
            String strDatabaseUsername = "root";
            String strDatabasePassword = "";
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
            System.out.println(error);
        }
    }
    
    public int incrementID(){
        String strID;
        int intID = 0;
        connectDatabase();
        String strquery = "SELECT student_ID from StudentList order by student_ID";
        try{
            pstmtMain = conMain.prepareStatement(strquery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                strID = rsMain.getString("student_ID");
                intID = Integer.parseInt(strID)+1;
            }
        }
        catch(SQLException error){
            System.out.println(error);
        }
        if(intID == 0){
            return 190000;
        }
        else{
            return intID;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfldID = new javax.swing.JTextField();
        tfldLName = new javax.swing.JTextField();
        tfldFName = new javax.swing.JTextField();
        pfldPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblRegistration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tfldID.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldID.setEnabled(false);

        tfldLName.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldLName.setText("Input Last Name");
        tfldLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldLNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldLNameFocusLost(evt);
            }
        });

        tfldFName.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldFName.setText("Input First Name");
        tfldFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldFNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldFNameFocusLost(evt);
            }
        });

        pfldPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pfldPassword.setText("()()()");
        pfldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfldPasswordFocusLost(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(241, 209, 165));
        btnRegister.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(56, 33, 29));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(241, 209, 165));
        btnCancel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(56, 33, 29));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblRegistration.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/las/images/library32.png"))); // NOI18N
        lblRegistration.setText("Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfldID)
                    .addComponent(tfldLName)
                    .addComponent(tfldFName)
                    .addComponent(pfldPassword)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pfldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfldLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldLNameFocusLost
        if(tfldLName.getText().equals("")){
            tfldLName.setText("Input Last Name");
        }
    }//GEN-LAST:event_tfldLNameFocusLost

    private void tfldFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldFNameFocusLost
        if(tfldFName.getText().equals("")){
            tfldFName.setText("Input First Name");
        }
    }//GEN-LAST:event_tfldFNameFocusLost

    private void tfldLNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldLNameFocusGained
        if(tfldLName.getText().equals("Input Last Name")){
            tfldLName.setText("");
        }
    }//GEN-LAST:event_tfldLNameFocusGained

    private void tfldFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldFNameFocusGained
        if(tfldFName.getText().equals("Input First Name")){
            tfldFName.setText("");
        }
    }//GEN-LAST:event_tfldFNameFocusGained

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        connectDatabase();
        String strID = tfldID.getText();
        String strLName = tfldLName.getText();
        String strFName = tfldFName.getText();
        String strUsername = ""+strLName.charAt(0)+strFName.charAt(0)+strID.substring(3);
        String strPassword = pfldPassword.getText();
        String strQuery = "INSERT INTO"
                + " StudentList (student_ID, student_LName, student_FName, student_Username, student_Password)"
                + " values("+strID+", '"+strLName+"', '"+strFName+"', '"+strUsername+"', '"+strPassword+"')";
        if(strLName.equals("")||strFName.equals("")||strPassword.equals("")){
            JOptionPane.showMessageDialog(null, "Fields must not be Blank.");
        }
        else{
            try{
                pstmtMain = conMain.prepareStatement(strQuery);
                pstmtMain.execute();
                JOptionPane.showMessageDialog(null, "Successfully Registered with Username of ["+strUsername+"].", "REGISTERED", JOptionPane.INFORMATION_MESSAGE);
                new FrLogin().setVisible(true);
                this.dispose();
            }
            catch(SQLException error){
                System.out.println(error);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new FrLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void pfldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfldPasswordFocusGained
        if(pfldPassword.getText().equals("()()()")){
            pfldPassword.setText("");
        }
    }//GEN-LAST:event_pfldPasswordFocusGained

    private void pfldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfldPasswordFocusLost
        if(pfldPassword.getText().equals("")){
            pfldPassword.setText("()()()");
        }
    }//GEN-LAST:event_pfldPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrStudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrStudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrStudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrStudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrStudentRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JPasswordField pfldPassword;
    private javax.swing.JTextField tfldFName;
    private javax.swing.JTextField tfldID;
    private javax.swing.JTextField tfldLName;
    // End of variables declaration//GEN-END:variables
}
