/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Imperator
 */
public class FrStudentHomePage extends javax.swing.JFrame {

    /**
     * Creates new form FrStudentHomePage
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    int intStudentID = 0;
    public FrStudentHomePage(int intStudentID) {
        this.intStudentID = intStudentID;
        labelBackground();
        initComponents();
        loadBookList();
    } 

    private FrStudentHomePage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void labelDialogBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/las/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(188, 131, java.awt.Image.SCALE_SMOOTH);
            dlgPassword.setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/las/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(676, 272, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    public void connectDatabase(){
        try{
            String strURL = "jdbc:mysql://localhost:3306/ls?useLegacyDatetimeCode=false&serverTimezone=UTC";
            String strDatabaseUsername = "root";
            String strDatabasePassword = "";
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
            System.out.println(error);
        }
    }
    
    public void loadBookList(String strSearch){
        connectDatabase();
        DefaultTableModel tblModel = (DefaultTableModel) tblList.getModel();
        tblModel.setRowCount(0);
        String strQuery = "SELECT book_ID, book_Name, book_Author from BookList order by book_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                String strID = rsMain.getString("book_ID");
                String strName = rsMain.getString("book_Name");
                String strAuthor = rsMain.getString("book_Author");
                if(strName.toLowerCase().contains(strSearch.toLowerCase())||strAuthor.toLowerCase().contains(strSearch.toLowerCase())){
                    tblModel.addRow(new Object[]{strID, strName, strAuthor});
                }
            }
        }
        catch(SQLException error){
            System.out.println(error);
        }
    }
    
    public void loadBookList(){
        connectDatabase();
        DefaultTableModel tblModel = (DefaultTableModel) tblList.getModel();
        tblModel.setRowCount(0);
        String strQuery = "SELECT book_ID, book_Name, book_Author from BookList order by book_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                String strID = rsMain.getString("book_ID");
                String strName = rsMain.getString("book_Name");
                String strAuthor = rsMain.getString("book_Author");
                tblModel.addRow(new Object[]{strID, strName, strAuthor});
            }
        }
        catch(SQLException error){
            System.out.println(error);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgPassword = new javax.swing.JDialog();
        tfldOldPassword = new javax.swing.JTextField();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblOldPassword = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        tfldNewPassword = new javax.swing.JTextField();
        scpList = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        tfldSearch = new javax.swing.JTextField();

        labelDialogBackground();
        dlgPassword.setMinimumSize(new java.awt.Dimension(188, 131));
        dlgPassword.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgPassword.setName("Change Password"); // NOI18N
        dlgPassword.setUndecorated(true);
        dlgPassword.setResizable(false);

        tfldOldPassword.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        btnAccept.setBackground(new java.awt.Color(241, 209, 165));
        btnAccept.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(241, 209, 165));
        btnCancel.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblOldPassword.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblOldPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblOldPassword.setText("Input Old Password:");

        lblNewPassword.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPassword.setText("Input New Password:");

        tfldNewPassword.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        javax.swing.GroupLayout dlgPasswordLayout = new javax.swing.GroupLayout(dlgPassword.getContentPane());
        dlgPassword.getContentPane().setLayout(dlgPasswordLayout);
        dlgPasswordLayout.setHorizontalGroup(
            dlgPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfldOldPassword)
                    .addGroup(dlgPasswordLayout.createSequentialGroup()
                        .addComponent(btnAccept)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addComponent(lblOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfldNewPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgPasswordLayout.setVerticalGroup(
            dlgPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOldPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tblList.setBackground(new java.awt.Color(241, 209, 165));
        tblList.setFont(new java.awt.Font("Lucida Console", 0, 10)); // NOI18N
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book", "Author"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.setSelectionBackground(new java.awt.Color(233, 123, 55));
        tblList.getTableHeader().setReorderingAllowed(false);
        scpList.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setResizable(false);
            tblList.getColumnModel().getColumn(1).setResizable(false);
            tblList.getColumnModel().getColumn(2).setResizable(false);
        }
        tblList.getTableHeader().setFont(new java.awt.Font("Lucida Console", 0, 18));

        btnLogout.setBackground(new java.awt.Color(241, 209, 165));
        btnLogout.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(241, 209, 165));
        btnChangePassword.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        tfldSearch.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        tfldSearch.setText("Search Here");
        tfldSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfldSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfldSearchFocusLost(evt);
            }
        });
        tfldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfldSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scpList, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(tfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new FrLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        dlgPassword.setLocationRelativeTo(null);
        dlgPassword.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void tfldSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldSearchFocusGained
        if(tfldSearch.getText().equals("Search Here")){
            tfldSearch.setText("");
        }
    }//GEN-LAST:event_tfldSearchFocusGained

    private void tfldSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfldSearchFocusLost
        if(tfldSearch.getText().equals("")){
            tfldSearch.setText("Search Here");
        }
    }//GEN-LAST:event_tfldSearchFocusLost

    private void tfldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfldSearchActionPerformed
        if(tfldSearch.equals("")){
            loadBookList();
        }
        else{
            loadBookList(tfldSearch.getText());
        }
    }//GEN-LAST:event_tfldSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        tfldNewPassword.setText("");
        tfldOldPassword.setText("");
        dlgPassword.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        connectDatabase();
        String strOldPassword = tfldOldPassword.getText();
        String strNewPassword = tfldNewPassword.getText();
        String strPassword = "UPDATE "
                + "studentList SET "
                + "student_Password = '"+strNewPassword+"' "
                + "WHERE student_ID = "+intStudentID;
        String strQuery = "SELECT "
                + "student_ID, student_Password "
                + "FROM studentList order by student_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                if(rsMain.getInt("student_ID") == intStudentID && rsMain.getString("student_Password").equals(strOldPassword)){
                    if(strNewPassword.equals("")){
                        java.awt.Toolkit.getDefaultToolkit().beep();
                    }
                    else{
                        System.out.println("CHANGE");
                        pstmtMain = conMain.prepareStatement(strPassword);
                        pstmtMain.execute();
                        tfldNewPassword.setText("");
                        tfldOldPassword.setText("");
                        dlgPassword.setVisible(false);
                    }
                }
            }
        }
        catch(SQLException error){
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrStudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrStudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrStudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrStudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrStudentHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLogout;
    private javax.swing.JDialog dlgPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JScrollPane scpList;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField tfldNewPassword;
    private javax.swing.JTextField tfldOldPassword;
    private javax.swing.JTextField tfldSearch;
    // End of variables declaration//GEN-END:variables
}
